### ISSUE TITLE
NullPointerException spam in IVA with crewed vessels.

### ISSUE THREAD

**Issue by ngx-ree** [JonnyOThan/KSP-ProbeControlRoom#39] opened 2024-10-31 03:41 UTC
When used on vessel with both drone core and crewed module, switching to cockpit IVA causes NullPointerException error messages loop spamming log and dropping framerate. Reviva mod is installed, testing with several different cockpits always does the same (even stock cockpit).

This happens after second IVA, so:

1. press 'c' -> IVA, ok
2. press 'c' -> PCR, ok
3. press 'c' -> outside, ok
4. press 'c' -> IVA - exceptions in loop, log spam, framerate drop
5. press 'c' -> PCR - a few exceptions, but not in loop

Every subsequent IVA generates errors in loop.

Also, once I noticed PCR had some elements from alternate IVA (MAS?), but usually it has only RPMs. Could not recreate it.
[KSP.log.zip](https://github.com/user-attachments/files/17581606/KSP.log.zip)

**Comment by JonnyOThan** [comment] 2024-11-11 21:39
Not yet sure where the issue is, but confirmed that it happens just by pressing C several times.

- still occurs without MAS installed
- still occurs without reviva
- Does not occur without FreeIva

**Comment by JonnyOThan** [comment] 2024-11-28 19:35
Fixed in FreeIva.

**Closed as completed by JonnyOThan** 2024-11-28 19:35 UTC
Labels: bug
